export enum EnvVar {
  PROJECT_ID = 'PROJECT_ID',
  API_KEY = 'API_KEY',
}

export enum EnvVarOptional {
  SCHEDULE_UNIT = 'SCHEDULE_UNIT',
  SCHEDULE_VALUE = 'SCHEDULE_VALUE',
  SCHEDULE_TS = 'SCHEDULE_TS',
  URLS = 'URLS',
  TEMPLATE_ID = 'TEMPLATE_ID',
}
