name: Publish

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: "test"
    steps:
      - uses: websiteshot/github-action@main
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          URL: "https://dev.to"
