name: Publish

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: "test"
    steps:
      - uses: websiteshot/github-action@main
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          URLS: '[{"url": "https://dev.to", "name": "DEV.to"}]'
          SCHEDULE_UNIT: "m"
          SCHEDULE_VALUE: "5"
